#!/bin/bash

if HOOKS_DEST="`git rev-parse --git-dir`/hooks"; then
	find "$HOOKS_DEST" ! -name '*.sample' -type f -exec rm {} +
	cp .hooks/* "$HOOKS_DEST/"
	git config --local trailer.sign.key "Signed-off-by: "
	git config --local trailer.sign.ifmissing add
	git config --local trailer.sign.ifexists doNothing
	git config --local trailer.sign.command 'echo "$(git config user.name) <$(git config user.email)>"'
	git config --local commit.template .gitmessage
fi
